"""Sine data for the legacy probe, generated by the CURRENT recipe.

This is a local, read-only copy of `_make_sin_dataset` / `load_sin_homo` from
`src/data.py`, with the training-set size lifted into a parameter so the probe
can run the N=50 variant without touching the live module. Nothing else is
changed: sigma = 0.1 constant, training grid on [0, 6], evaluation grid of
1000 points on [-2, 8], seed 42, and the same single RandomState stream used
first for the training noise and then for `y_eval_noisy`.

`check_matches_live()` asserts that N=250 here reproduces `src.data.load_sin_homo`
exactly, so any difference seen in the notebooks comes from the METHODS, not
from a drifted copy of the data recipe.

The recipe was copied from the `ml_uncertainty_msc` repository, so the check is
pinned to THAT tree by absolute path (`REFERENCE_REPO`, overridable with the
`ML_UNCERTAINTY_REPO` environment variable). This folder now lives next to a
different, older copy of the project whose `src/data.py` has no `load_sin_homo`
at all — importing whatever `src` happens to be on `sys.path` would compare
against the wrong recipe, or fail confusingly.
"""
import os
import sys
from dataclasses import dataclass
from pathlib import Path

import numpy as np

REFERENCE_REPO = Path(os.environ.get(
    "ML_UNCERTAINTY_REPO", r"C:/Users/michal/Desktop/ml_uncertainty_msc"))

EVAL_GRID_N = 1000
EVAL_LO, EVAL_HI = -2.0, 8.0
TRAIN_LO, TRAIN_HI = 0.0, 6.0


@dataclass
class SinData:
    name: str
    X_train: np.ndarray
    y_train: np.ndarray
    X_eval: np.ndarray
    y_eval: np.ndarray        # clean f(x) -- the dashed line, plotting only
    y_eval_noisy: np.ndarray  # f(x) + fresh noise -- what metrics would use
    sigma_true_train: np.ndarray
    sigma_true_eval: np.ndarray


def _sigma_homo(x: np.ndarray) -> np.ndarray:
    return np.full_like(x, 0.1)


def make_sin_homo(n_train: int = 250, seed: int = 42) -> SinData:
    """f(x) = sin(x), sigma = 0.1 constant, train on [0, 6], eval on [-2, 8]."""
    X_train = np.linspace(TRAIN_LO, TRAIN_HI, n_train).reshape(-1, 1)

    rng = np.random.RandomState(seed)
    x_train_flat = X_train.ravel()
    sigma_train = _sigma_homo(x_train_flat)
    y_train = np.sin(x_train_flat) + sigma_train * rng.randn(len(x_train_flat))

    X_eval = np.linspace(EVAL_LO, EVAL_HI, EVAL_GRID_N).reshape(-1, 1)
    x_eval_flat = X_eval.ravel()
    y_eval = np.sin(x_eval_flat)
    sigma_eval = _sigma_homo(x_eval_flat)
    y_eval_noisy = np.sin(x_eval_flat) + sigma_eval * rng.randn(len(x_eval_flat))

    return SinData(
        name=f"sin_homo_n{n_train}",
        X_train=X_train.astype(np.float64),
        y_train=y_train.astype(np.float64),
        X_eval=X_eval.astype(np.float64),
        y_eval=y_eval.astype(np.float64),
        y_eval_noisy=y_eval_noisy.astype(np.float64),
        sigma_true_train=sigma_train.astype(np.float64),
        sigma_true_eval=sigma_eval.astype(np.float64),
    )


def check_matches_live() -> str:
    """Assert the N=250 copy is bit-identical to the reference `load_sin_homo`.

    Raises if the reference tree is reachable and the arrays disagree. Returns a
    SKIPPED message if the tree is simply not there (this folder is designed to
    be deletable and movable, so a missing reference is not an error) — the
    stored notebook outputs record the check passing at build time.
    """
    if not (REFERENCE_REPO / "src" / "data.py").is_file():
        return (f"CHECK SKIPPED: reference repo not found at {REFERENCE_REPO} "
                f"(set ML_UNCERTAINTY_REPO to point at it)")

    if str(REFERENCE_REPO) not in sys.path:
        sys.path.insert(0, str(REFERENCE_REPO))
    from src.data import load_sin_homo

    live = load_sin_homo(seed=42)
    mine = make_sin_homo(n_train=250, seed=42)
    for field in ("X_train", "y_train", "X_eval", "y_eval",
                  "y_eval_noisy", "sigma_true_train", "sigma_true_eval"):
        np.testing.assert_array_equal(getattr(live, field), getattr(mine, field),
                                      err_msg=f"{field} drifted from src.data")
    return (f"OK: make_sin_homo(250) == load_sin_homo() on all 7 arrays "
            f"(reference: {REFERENCE_REPO})")
